name: Publish Package

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          scope: '@dplei'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.10.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Debug pnpm registry
        run: pnpm config get registry

      - name: Build
        if: false
        run: npm run build

      - name: Debug npm registry for npm
        run: npm config get registry

      - name: Publish to npm
        if: false
        run: npm publish --access public --registry=https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Set npm registry to GitHub Packages
        run: npm config set registry https://npm.pkg.github.com/

      - name: Debug npm registry for GitHub Packages
        run: npm config get registry

      - name: Publish to GitHub Packages
        if: false
        run: |
          npm config set registry https://npm.pkg.github.com/
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
